name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        name: 'Setup node'
        with:
          node-version: '16.x'
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      # - name: Install dependencies
      #   uses: ianwalter/puppeteer-container@acc52cd2334ad9eaf6e1974562d263e0a711b7e8
      #   with:
      #     args: yarn install --frozen-lockfile
      # - name: Build Extension app
      #   uses: ianwalter/puppeteer-container@acc52cd2334ad9eaf6e1974562d263e0a711b7e8
      #   with: 
      #     args: yarn build
      # - name: Run e2e tests
      #   uses: ianwalter/puppeteer-container@acc52cd2334ad9eaf6e1974562d263e0a711b7e8
      #   with: 
      #     args: yarn e2e
      # - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build Extension app
        run: yarn build
      - name: Run e2e tests
        run: yarn e2e
      - run: echo "ğŸ This job's status is ${{ job.status }}."
