name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      # - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      # - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      # - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # - name: Check out repository code
      #   uses: actions/checkout@v3
      # - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      # - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          node-version: '16.x'
      - run: npm i -g yarn
      - run: yarn
      - run: yarn build

      # - name: Install Yarn
      #   run: npm i -g yarn
      # - name: Install dependencies
      #   run: yarn install --frozen-lockfile

      - name: Test Code
        uses: mujo-code/puppeteer-headful@v2
        env:
          CI: 'true'
        with:
          args: yarn e2e
      # - name: Build Extension app
      #   run: yarn build
      # - name: Run e2e tests
      #   run: yarn e2e
      # - run: echo "ğŸ This job's status is ${{ job.status }}."
